name: Taipower Crawler

on:
  schedule:
    - cron: "0 * * * *"   # 每小時執行一次 (UTC 時區)
  workflow_dispatch:       # 手動觸發

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run crawler
        run: python crawler.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add taipower_emission_data.csv
          git commit -m "Update data [skip ci]" || echo "No changes to commit"
          git push
